# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app
COPY package.json package-lock.json ./
COPY src ./src
RUN npm ci
CMD ["node","src/test_stdio_list.js"]
